### ISSUE TITLE
statically obtain the types of an OCL expression of ETL

### ISSUE THREAD

**Issue by BanafshehAzizi** [epsilonlabs/haetae#2]
How can I obtain the types of an OCL expression of ETL transformation by Haetae? (the model with the OCL navigations parsed)

**Comment by wrwei** [comment]
Hi there,

To obtain the types of expression of an ETL transformation, Haetae provides an "overview" view to view the entire tree of the program. However, like OCL, Haetae provides a "best guess" solution. Expressions with type "Any" will be recorded as "Any" on the overview, although internally different things happen.

Hope this helps.

Cheers,
Will

**Comment by BanafshehAzizi** [comment]
thanks, How can I detect OCL expressions and their type through this tree (ETL model)?

**Comment by wrwei** [comment]
In the tree you should search for instances of FOLMethodCallExpression, which are first order logic expressions
